Add some Gradle tasks
Pylo/MCreatorDemoPlugin pull request #4
Opened 2021-10-28 02:10 UTC by Goldorion

In my plugins, I started to use Gradle to simplify the repetitive tasks of building, installing and launching MCreator. So I decided to add them to this plugin template, so more users can use them to be quicker at testing their plugins. Current tasks are:

- Build the plugin
- Install it
- Launch MCreator

I also move files and folders related to the demo plugin inside an `src` folder, as the build task only works this way. I also renamed `1.14.4` and `1.15.2` folders to `forge-1.14.4` and `forge-1.15.2`.

2021-10-28 02:23 UTC, Goldorion commented
How can I not push files into the `.idea` folder?

2021-10-28 08:20 UTC, KlemenDEV commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be in gitignore

2021-10-28 10:37 UTC, Goldorion commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
The file os already in the gitignore. This is why I asked how can I not push those files.

2021-10-28 11:11 UTC, KlemenDEV commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
When you used git add ., you should not add these. You will need to rm it probably

2021-10-29 15:00 UTC, Goldorion commented
I found back the [code of BoogieMonster101](https://github.com/Goldorion/Fabric-Generator-MCreator/commit/66e1ea29d4b11e8aaeb55d1da093b06adf7008b3#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R40) for the launch task on mac and Linux, so I added it. I obviously can't test it, but as he didn't change it after, it should work.

2021-10-29 18:05 UTC, KlemenDEV requested changes
I would update Exporting readme section to include gradle task, rename build task to "export" and make new task group called "mcreator_plugin" for these tasks. Other than that, all good :)

2021-10-30 08:13 UTC, KlemenDEV approved these changes

2021-10-30 08:13 UTC, merged